// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// QuestionSequence is an object representing the database table.
type QuestionSequence struct {
	N int64 `boil:"n" json:"n" toml:"n" yaml:"n"`

	R *questionSequenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L questionSequenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QuestionSequenceColumns = struct {
	N string
}{
	N: "n",
}

var QuestionSequenceTableColumns = struct {
	N string
}{
	N: "question_sequence.n",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var QuestionSequenceWhere = struct {
	N whereHelperint64
}{
	N: whereHelperint64{field: "\"question_sequence\".\"n\""},
}

// QuestionSequenceRels is where relationship names are stored.
var QuestionSequenceRels = struct {
}{}

// questionSequenceR is where relationships are stored.
type questionSequenceR struct {
}

// NewStruct creates a new relationship struct
func (*questionSequenceR) NewStruct() *questionSequenceR {
	return &questionSequenceR{}
}

// questionSequenceL is where Load methods for each relationship are stored.
type questionSequenceL struct{}

var (
	questionSequenceAllColumns            = []string{"n"}
	questionSequenceColumnsWithoutDefault = []string{}
	questionSequenceColumnsWithDefault    = []string{"n"}
	questionSequencePrimaryKeyColumns     = []string{"n"}
	questionSequenceGeneratedColumns      = []string{}
)

type (
	// QuestionSequenceSlice is an alias for a slice of pointers to QuestionSequence.
	// This should almost always be used instead of []QuestionSequence.
	QuestionSequenceSlice []*QuestionSequence

	questionSequenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	questionSequenceType                 = reflect.TypeOf(&QuestionSequence{})
	questionSequenceMapping              = queries.MakeStructMapping(questionSequenceType)
	questionSequencePrimaryKeyMapping, _ = queries.BindMapping(questionSequenceType, questionSequenceMapping, questionSequencePrimaryKeyColumns)
	questionSequenceInsertCacheMut       sync.RWMutex
	questionSequenceInsertCache          = make(map[string]insertCache)
	questionSequenceUpdateCacheMut       sync.RWMutex
	questionSequenceUpdateCache          = make(map[string]updateCache)
	questionSequenceUpsertCacheMut       sync.RWMutex
	questionSequenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single questionSequence record from the query using the global executor.
func (q questionSequenceQuery) OneG(ctx context.Context) (*QuestionSequence, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single questionSequence record from the query.
func (q questionSequenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*QuestionSequence, error) {
	o := &QuestionSequence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for question_sequence")
	}

	return o, nil
}

// AllG returns all QuestionSequence records from the query using the global executor.
func (q questionSequenceQuery) AllG(ctx context.Context) (QuestionSequenceSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all QuestionSequence records from the query.
func (q questionSequenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (QuestionSequenceSlice, error) {
	var o []*QuestionSequence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to QuestionSequence slice")
	}

	return o, nil
}

// CountG returns the count of all QuestionSequence records in the query using the global executor
func (q questionSequenceQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all QuestionSequence records in the query.
func (q questionSequenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count question_sequence rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q questionSequenceQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q questionSequenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if question_sequence exists")
	}

	return count > 0, nil
}

// QuestionSequences retrieves all the records using an executor.
func QuestionSequences(mods ...qm.QueryMod) questionSequenceQuery {
	mods = append(mods, qm.From("\"question_sequence\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"question_sequence\".*"})
	}

	return questionSequenceQuery{q}
}

// FindQuestionSequenceG retrieves a single record by ID.
func FindQuestionSequenceG(ctx context.Context, n int64, selectCols ...string) (*QuestionSequence, error) {
	return FindQuestionSequence(ctx, boil.GetContextDB(), n, selectCols...)
}

// FindQuestionSequence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQuestionSequence(ctx context.Context, exec boil.ContextExecutor, n int64, selectCols ...string) (*QuestionSequence, error) {
	questionSequenceObj := &QuestionSequence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"question_sequence\" where \"n\"=?", sel,
	)

	q := queries.Raw(query, n)

	err := q.Bind(ctx, exec, questionSequenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from question_sequence")
	}

	return questionSequenceObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *QuestionSequence) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *QuestionSequence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no question_sequence provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(questionSequenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	questionSequenceInsertCacheMut.RLock()
	cache, cached := questionSequenceInsertCache[key]
	questionSequenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			questionSequenceAllColumns,
			questionSequenceColumnsWithDefault,
			questionSequenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(questionSequenceType, questionSequenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(questionSequenceType, questionSequenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"question_sequence\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"question_sequence\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into question_sequence")
	}

	if !cached {
		questionSequenceInsertCacheMut.Lock()
		questionSequenceInsertCache[key] = cache
		questionSequenceInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single QuestionSequence record using the global executor.
// See Update for more documentation.
func (o *QuestionSequence) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the QuestionSequence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *QuestionSequence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	questionSequenceUpdateCacheMut.RLock()
	cache, cached := questionSequenceUpdateCache[key]
	questionSequenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			questionSequenceAllColumns,
			questionSequencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update question_sequence, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"question_sequence\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, questionSequencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(questionSequenceType, questionSequenceMapping, append(wl, questionSequencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update question_sequence row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for question_sequence")
	}

	if !cached {
		questionSequenceUpdateCacheMut.Lock()
		questionSequenceUpdateCache[key] = cache
		questionSequenceUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q questionSequenceQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q questionSequenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for question_sequence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for question_sequence")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o QuestionSequenceSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QuestionSequenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionSequencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"question_sequence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionSequencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in questionSequence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all questionSequence")
	}
	return rowsAff, nil
}

// DeleteG deletes a single QuestionSequence record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *QuestionSequence) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single QuestionSequence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *QuestionSequence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no QuestionSequence provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), questionSequencePrimaryKeyMapping)
	sql := "DELETE FROM \"question_sequence\" WHERE \"n\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from question_sequence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for question_sequence")
	}

	return rowsAff, nil
}

func (q questionSequenceQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q questionSequenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no questionSequenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from question_sequence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for question_sequence")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o QuestionSequenceSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QuestionSequenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionSequencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"question_sequence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionSequencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from questionSequence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for question_sequence")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *QuestionSequence) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no QuestionSequence provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *QuestionSequence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindQuestionSequence(ctx, exec, o.N)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuestionSequenceSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty QuestionSequenceSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QuestionSequenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QuestionSequenceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), questionSequencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"question_sequence\".* FROM \"question_sequence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, questionSequencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in QuestionSequenceSlice")
	}

	*o = slice

	return nil
}

// QuestionSequenceExistsG checks if the QuestionSequence row exists.
func QuestionSequenceExistsG(ctx context.Context, n int64) (bool, error) {
	return QuestionSequenceExists(ctx, boil.GetContextDB(), n)
}

// QuestionSequenceExists checks if the QuestionSequence row exists.
func QuestionSequenceExists(ctx context.Context, exec boil.ContextExecutor, n int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"question_sequence\" where \"n\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, n)
	}
	row := exec.QueryRowContext(ctx, sql, n)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if question_sequence exists")
	}

	return exists, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *QuestionSequence) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *QuestionSequence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no question_sequence provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(questionSequenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	questionSequenceUpsertCacheMut.RLock()
	cache, cached := questionSequenceUpsertCache[key]
	questionSequenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			questionSequenceAllColumns,
			questionSequenceColumnsWithDefault,
			questionSequenceColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			questionSequenceAllColumns,
			questionSequencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert question_sequence, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(questionSequencePrimaryKeyColumns))
			copy(conflict, questionSequencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"question_sequence\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(questionSequenceType, questionSequenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(questionSequenceType, questionSequenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert question_sequence")
	}

	if !cached {
		questionSequenceUpsertCacheMut.Lock()
		questionSequenceUpsertCache[key] = cache
		questionSequenceUpsertCacheMut.Unlock()
	}

	return nil
}
